RestaurationApp/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RestaurationApp.Services.Interfaces;
using RestaurationApp.ViewModels;

namespace RestaurationApp.Controllers
{
    public class MenuController : Controller
    {
        private IDishService _dish;

        public MenuController(IDishService dish)
        {
            _dish = dish;
        }

        public IActionResult Index()
        {
            var model = new MenuViewModel();
            model.Dishes = _dish.GetAll();
            return View(model);
        }

        public IActionResult Cuisines()
        {
            var model = new CuisinesViewModel();
            model.cuisines = _dish.GetAllCuisines();
            return View(model);
        }
        /// <summary>
        /// Zwraca wszystkie dania z danej kuchni
        /// </summary>
        /// <param name="Id">Parametr okresla id kuchni</param>
        /// <returns></returns>
        public IActionResult Cuisine(int Id)
        {
            var model = new MenuViewModel();
            model.Dishes = _dish.GetDishesFromCuisine(Id);
            return View(model);
        }

        public IActionResult DishDetail(int Id)
        {
            var model = _dish.GetDishDetailObject(Id);

            return View(model);
        }
    }
}

RestaurationApp/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurationApp.Models;
using RestaurationApp.Services.Interfaces;
using RestaurationApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurationApp.Controllers
{
    public class TeamController : Controller
    {
        private IPersonService _person;

        public TeamController(IPersonService person)
        {
            _person = person;
        }

        public IActionResult OurStuff()
        {
            var model = new StuffViewModel();
            model.People = _person.GetAllPeople();

            return View(model);
        }
    }
}

RestaurationApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] | RestaurationApp</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    </head>
<body>
    <div id="AppBox">
        <header>
            <div class="container">
                <div id="logo">
                    <h1>App <span class="highlight">Restauration </span></h1>
                </div>
                <nav>
                    <ul>
                        <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                        <li><a asp-action="Cuisines" asp-controller="Menu">Menu</a></li>
                        <li><a asp-action="OurStuff" asp-controller="Team">Our Stuff</a></li>
                    </ul>
                </nav>
            </div>
        </header>

        <section id="showcase">
            <div class="container">
                <h1>Restaurant Application</h1>
                <p>We serve best dishes from diffrent cuisines. Our price is right in relation to quality.</p>
            </div>
        </section>

        @RenderBody()
        <footer>
            <p>Tomasz Kubik, Copyright &copy; 2019</p>
        </footer>
    </div>
</body>